export const initialGame = {
    'a1': 'black_rook',
    'a2': 'black_knight',
    'a3': 'black_bishop',
    'a4': 'black_queen',
    'a5': 'black_king',
    'a6': 'black_bishop',
    'a7': 'black_knight',
    'a8': 'black_rook',
    'a9': 'black_pawn',
    'a10': 'black_pawn',
    'a11': 'black_pawn',
    'a12': 'black_pawn',
    'a13': 'black_pawn',
    'a14': 'black_pawn',
    'a15': 'black_pawn',
    'a16': 'black_pawn',
    
    'a57': 'white_rook',
    'a58': 'white_knight',
    'a59': 'white_bishop',
    'a60': 'white_queen',
    'a61': 'white_king',
    'a62': 'white_bishop',
    'a63': 'white_knight',
    'a64': 'white_rook',
    'a49': 'white_pawn',
    'a50': 'white_pawn',
    'a51': 'white_pawn',
    'a52': 'white_pawn',
    'a53': 'white_pawn',
    'a54': 'white_pawn',
    'a55': 'white_pawn',
    'a56': 'white_pawn',
}